### ISSUE TITLE
rln is missing

### ISSUE THREAD

**Issue by WizardOfWor1969** [mwenge/vlm#1]
submodule rln is missing

**Comment by mwenge** [comment]
I can't replicate this! 

robert@mwenge-desktop vlm (master)]$ git submodule init                                                                              
Submodule 'rln' (http://shamusworld.gotdns.org/git/rln) registered for path 'rln'
Submodule 'rmac' (git@github.com:mwenge/rmac.git) registered for path 'rmac'
[robert@mwenge-desktop vlm (master)]$ git submodule update                                                                            
Cloning into '/home/robert/Dev/vlm/rln'...                                                                                                                                                                                                                                   
Cloning into '/home/robert/Dev/vlm/rmac'...                                                                                           
Submodule path 'rln': checked out 'a839b5e1b42ccc20bc7a0960c79c6916415adffb'                                                          
Submodule path 'rmac': checked out '50e66eaba10807de992792daaf700b6575ef43a6'

**Comment by WizardOfWor1969** [comment]
I guess it's something on my end, but I continue to get this error...

![Screen Shot 2021-08-05 at 12 58 57 PM](https://user-images.githubusercontent.com/52321250/128413285-2ff27482-e87b-4078-aa8d-80bc9b0be5fc.png)
